$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  output_folder:
    type: string
  metagenomes:
    type: object
    properties:
      assemble_contigs:
        type: string
      contigs_ext:
        type: string
      reads_folder:
        type: string
      reads_identifier:
        type: string
    required:
      - reads_folder
      - contigs_ext
      - assemble_contigs
      - reads_identifier
  default_blast_option:
    type: object
    properties:
      e_val:
        type: number
        minimum: 0
        maximum: 1
      coverage:
        type: number
        minimum: 0
        maximum: 1    
      pident:
        type: number
        minimum: 0
        maximum: 1 
      cov_min:
        type: string
        enum: ["mean","subject", "query", "shortest", "longest"]
      pid_min:
        type: string
        enum: ["mean","subject", "query", "shortest", "longest", "HSP"]
      length_min:
        type: number
    required:
      - cov_min
      - pid_min
      - length_min
      - e_val
      - coverage
  iphop_db:
    type: string
  genomad:
    type: object
    properties:
      path:
        type: string
      composition:
        type: string
        enum: ["virome", "metagenome"]
    required:
      - path
      - composition
  database:
    type: object
    properties:
      ICTV:
        type: object
        properties:
          path:
            type: string
          metadata:
            type: string
        required:
          - path
          - type
      refseq_viral:
        type: object
        properties:
          path:
            type: string
          metadata:
            type: string
        required:
          - path
          - type
      crassphage:
        type: object
        properties:
          path:
            type: string
        required:
          - path
      IMG_VR:
        type: object
        properties:
          path:
            type: string
          metadata:
            type: string
        required:
          - path
          - type
    required:
      - ICTV
      - refseq_viral
      - IMG_VR
      - crassphage
required:
  - metagenomes
  - output_folder
  - default_blast_option
  - iphop_db
  - genomad
  - databases